networks:
  shared_network:
    external: true

services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch01
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - shared_network
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      retries: 5
      start_period: 30s

  kibana01:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana01
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch01:9200
      NODE_OPTIONS: "--max-old-space-size=512"
    networks:
      - shared_network
    depends_on:
      elasticsearch01:
        condition: service_healthy
